---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    # ignore rake tasks
    - 'lib/rordan_gramsay/chef_tasks/**/*'
    - 'lib/rordan_gramsay/chef_tasks.rb'
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 12

Naming/FileName:
  Exclude:
    - '.simplecov'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

# These two are for supporting usage of the `paint` gem
Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
